config/routes.rb
GamefactoryTest::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations"}

  # catch attempts to access /users/password with a get (in cases where you mess up on password reminder and then try to access url directly)
  get '/users/password' => redirect('/users/password/new')

  # home routes
  root :to => 'home#index'
  get '/feed' => 'home#feed'

  # -- legacy redirects (from the previous architecture/db)
  get '/ideas/build', to: redirect { |params, request| "/ideas/browse?#{request.query_string}" }

  # dashboard
  scope '/dashboard' do
    get '/counts_for_owned_ideas/(:view_date)' => 'dashboard#counts_for_owned_ideas'
    get '/counts_for_followed_ideas/(:view_date)' => 'dashboard#counts_for_followed_ideas'
    get '/counts_for_navigation/(:view_date)' => 'dashboard#counts_for_navigation'

    get '/users_ideas' => 'dashboard#users_ideas'
    get '/followed_ideas' => 'dashboard#followed_ideas'
    get '/news' => 'dashboard#news'
    get '/posts_made_or_commented_on' => 'dashboard#posts_made_or_commented_on'
    get '/mentions' => 'dashboard#mentions'
    get '/more/(:what)/(:page)' => 'dashboard#more'    
  end

  # custom user routes
  get '/profile', to: 'user_profiles#show', :as => :my_profile
  post '/profile/search', :to => 'user_profiles#search', :as => :search_for_user
  get '/profile(/:id)', to: 'user_profiles#show', :as => :user, :constraints => { :id => /.*/ }
  get '/notification_settings' => 'notification_settings#edit'
  post '/notification_settings' => 'notification_settings#update', :as => :update_notification_settings
  get '/user_details' => 'user_details#edit'
  post '/user_details' => 'user_details#update', :as => :update_user_details
  post '/save_selection' => 'user_api#save_selection'
  post '/save_view' => 'user_api#save_viewed'
  post '/search_users' => 'user_api#search_users'

  # static pages
  get '/about' => 'pages#about'
  get '/about_team' => 'pages#about_team'
  get '/terms' => 'pages#terms'
  get '/faq' => 'pages#faq'
  get '/funding_info' => 'pages#funding_info'
  get '/volunteers' => 'pages#volunteers'
  get '/dev_center' => 'pages#dev_center'
  get '/dev_center_learn' => 'pages#dev_center_learn'
  get '/dev_center_build' => 'pages#dev_center_build'
  get '/community' => 'pages#community'
  get '/help' => 'pages#help'
  get '/news' => 'pages#news' # list of all news items, seperate from the dashboard list of news items
  get '/thanks_signup' => 'pages#thanks_signup', :as => 'thanks_signup'
  get '/about_reputation(/:user)' => 'pages#reputation', :as => 'about_reputation'

  # admin pages
  scope '/admin' do
    get '' => 'admin#index', as: 'admin'
    get 'top_voted' => 'admin#top_voted'
    get 'users' => 'admin#users'
    get 'user_metrics' => 'admin#user_metrics'
    get 'homepage_features' => 'admin#homepage_features'
    get 'generate_email_list' => 'admin#generate_email_list'
    get 'idea_metrics' => 'admin#idea_metrics'

    post 'set_homepage_features' => 'admin#set_homepage_features'

    get 'new_admin', :controller => 'admin'
    post 'adminify', :controller => 'admin'

    get 'news_alert', :controller => 'admin'
    post 'set_news_alert', :controller => 'admin'
    put 'set_news_alert', :controller => 'admin'
    post 'kill_news_alert', :controller => 'admin'

    # file moderation
    get 'files' => 'admin_files#unchecked', :as => 'admin_files'
    get 'files/checked' => 'admin_files#checked', :as => 'admin_files_checked'
    post 'files/mark_checked' => 'admin_files#mark_checked', :as => 'admin_files_mark_checked'
  end

  resources :comments
  resources :posts do
    member do
      post 'vote'
      get 'more_comments/(:page)' => 'posts#more_comments', :as => :more_comments
      
      get 'upload_files' => 'posts#upload_files'
      post 'upload_completed' => 'posts#upload_completed'
    end
  end


  resources :ideas, :except => :index do
    resources :goals
    resources :design_docs

    collection do
      get 'browse' => 'ideas_collection#browse'
      get 'play' => 'ideas_collection#play'
      get 'help_out'=> 'ideas_collection#help_out'
      get 'search' => 'ideas_collection#search'

      get '/(:browsing_for)/more/(:page)' => 'ideas_collection#more', :as => 'more'
    end

    member do
      # -- special page for deleted ideas
      get 'deleted' => 'ideas#deleted'
      
      # -- design document routes
      get 'design_document'
      post 'add_gallery_image' => 'idea_details#add_gallery_image'
      post 'remove_gallery_image' => 'idea_details#remove_gallery_image'
      post 'edit_banner_image' => 'idea_details#edit_banner_image'
      post 'edit_details' => 'idea_details#edit_details'
      post 'add_gallery_demo' => 'idea_details#add_gallery_demo'
      post 'remove_gallery_demo' => 'idea_details#remove_gallery_demo'
      post 'select_featured_demo' => 'idea_details#select_featured_demo'

      # -- checklist
      get 'checklist'
      post 'checklist/toggle_task' => 'ideas#toggle_checklist_task'

      # -- show more posts
      get 'more_posts/(:page)' => 'ideas#more_posts'

      # -- follow/unfollow
      post 'follow' => 'follows#create'
      delete 'unfollow' => 'follows#destroy'

      # -- yes/un-yes
      post 'yes' => 'yeses#create'
      delete 'no' => 'yeses#destroy'
    end
  end

  # -- resolve a goal using a post
  post '/resolve_goal' => 'goals#resolve'

  resources :feedback, :except => [:destroy] do
    member do
      post 'change_logged'
    end

    collection do
      get 'thank_you'      
    end
  end

  resources :news_items do
    collection do
      get 'admin' => 'news_items#admin'
    end
  end

  # -- alternate site activity view
  get 'site_activity' => 'site_activity#index', :as => 'site_activity'
  get 'site_activity/more/(:page)' => 'site_activity#more'

  # Vanilla forum single sign on using jsConnect
  get 'forum/single_sign_on' => 'vanilla_forum#single_sign_on'
  get 'forum' => 'vanilla_forum#embedded_forum'

  # Generic file upload (not tied to a post directly, just to a user)
  get 'files/(:user)/all' => 'files#all', :as => 'all_files'
  get 'files/(:user)' => 'files#index', :as => 'files'
  post 'files/upload_complete' => 'files#upload_complete'  

  # test s3 direct file upload setup
  # get 'upload_files' => 'test#upload_files'
  # post 'upload_completed' => 'test#upload_completed'  
end

app/views/admin/generate_email_list.html.haml
Linebreak-seperated list of user emails, as of #{get_formatted_date(@date, :include_time => true)}
\
\

- @users.each do |user|
  = user.email

app/views/admin/homepage_features.html.haml
= title "Admin - Edit Homepage Features"

For the following fields, just enter in the idea id and/or prototype id.
%br
%br

- current_features = HomepageFeatures.last
- if !current_features.nil?
	- current_ideas = current_features.get_ideas
	- current_demos = current_features.get_demos

	= form_for :admin, :url => set_homepage_features_path, :method => :post do |f|
		Idea 1 (#{current_ideas[0].details.title unless current_ideas[0].nil? }) : 
		= f.text_field :idea1, :value => current_features.idea1
		%br
		Idea 2 (#{current_ideas[1].details.title unless current_ideas[1].nil? }) : 
		= f.text_field :idea2, :value => current_features.idea2
		%br
		Idea 3 (#{current_ideas[2].details.title unless current_ideas[2].nil? }) : 
		= f.text_field :idea3, :value => current_features.idea3
		%br
		Idea 4 (#{current_ideas[3].details.title unless current_ideas[3].nil? }) : 
		= f.text_field :idea4, :value => current_features.idea4
		%br
		%br
		%br
		Demo 1 Idea (#{current_demos[0].idea.details.title unless current_demos[0].nil? }) : 
		= f.text_field :demo1_idea, :value => current_features.demo1_idea
		Demo 1 (#{current_demos[0].title unless current_demos[0].nil?}) :
		= f.text_field :demo1, :value => current_features.demo1
		%br
		Demo 2 Idea (#{current_demos[1].idea.details.title unless current_demos[1].nil? }) : 
		= f.text_field :demo2_idea, :value => current_features.demo2_idea
		Demo 2 (#{current_demos[1].title unless current_demos[1].nil?}) :
		= f.text_field :demo2, :value => current_features.demo2
		%br
		Demo 3 Idea (#{current_demos[2].idea.details.title unless current_demos[2].nil? }) : 
		= f.text_field :demo3_idea, :value => current_features.demo3_idea
		Demo 3 (#{current_demos[2].title unless current_demos[2].nil?}) :
		= f.text_field :demo3, :value => current_features.demo3
		%br
		%br
		%br
		= f.submit "submit"
-else
	= form_for :admin, :url => set_homepage_features_path, :method => :post do |f|
		Idea 1 : 
		= f.text_field :idea1
		%br
		Idea 2 : 
		= f.text_field :idea2
		%br
		Idea 3 : 
		= f.text_field :idea3
		%br
		Idea 4 : 
		= f.text_field :idea4
		%br
		%br
		%br
		Demo 1 Idea : 
		= f.text_field :demo1_idea
		Demo1 
		= f.text_field :demo1
		%br
		Demo 2 Idea : 
		= f.text_field :demo2_idea
		Demo 2 :
		= f.text_field :demo2
		%br
		Demo 3 Idea : 
		= f.text_field :demo3_idea
		Demo 3 :
		= f.text_field :demo3
		%br
		%br
		%br
		= f.submit "submit"

app/views/admin/idea_metrics.html.haml
= title "View New Idea Stats - Admin - GameSprout"
= content_for(:extra_early_javascripts) do
	= javascript_include_tag "http://www.google.com/jsapi"

%h3 Ideas - #{Idea.count} total
%br
%h3 TaskList Usage in Ideas
#admin-visualization-idea-task
	%br
- @total_tasklisters = 0
#admin-idea-task-vis-chart-data{:style => "display: none;"}
	%table
		- Idea.each do |idea|
			%tr
				%td
					= idea.created_at.month.to_s + "/" + idea.created_at.year.to_s
				%td
					= (is_task_used?(idea)) ? "#{1}" : "#{0}"
			- if( is_task_used?(idea) )
				- @total_tasklisters += 1

%h4 Total Ideas that Use TaskList: #{@total_tasklisters} of #{Idea.count} (#{(@total_tasklisters.to_f / Idea.count.to_f * 100).round(2)}%)
%br
%br

app/views/admin/index.html.haml
= title "Admin - GameSprout"

%main.content.admin
  %h4.centered Total Users: #{User.count}

  %h1 Admin Actions
  %nav.account
    %ul.unstyled
      %li= link_to "Manage News Items", admin_news_items_path
      %li= link_to "Manage Homepage Features", homepage_features_path
      %li= link_to "View Feedback", feedback_index_path
      %li= link_to "User Metrics",  user_metrics_path
      %li= link_to "New User Stats", users_path
      %li= link_to "Idea Stats", idea_metrics_path
      %li= link_to "Generate Email List", generate_email_list_path
      %li= link_to "New Admin", new_admin_path
      %li= link_to "Manage News Alert", news_alert_path
      %li= link_to "View Site Activity", site_activity_path
      %li= link_to "Check Uploaded Files", admin_files_path

app/views/admin/new_admin.html.haml
Enter an email, username or user id to adminify:

#find-user
  = form_tag search_for_user_path, :method => :post, :remote => true do
    = text_field_tag :find_by
    = button_tag 'Find User'

    %img.ajax-loader{src: '/assets/ajax-loader.gif', style: 'display: none;'}

%br
#hidden{:style => 'display: none;'}
  = form_tag adminify_path do
    
    #info
      %p Username: <span id='username'></span>
      %p Email: <span id='email'></span>
      %p Id: <span id='id'></span>
      %p Admin?: <span id='is-admin'></span>
      
      %br

    = hidden_field :user_id, '', :id => 'user-id'
    = submit_tag '', :id => 'submit'

%br

app/views/admin/news_alert.html.haml
= render :partial => 'shared/errors', :locals => {doc: @news_alert, centered: false}

- if @news_alert
  %h3 Current news alert:
  %br
  %p= raw @news_alert.text
  %br
  %p 
    %strong Stops on: 
    = get_formatted_date(@news_alert.stop_at)

- else
  %p No current news alert.

%br
%br

%h3 Set or replace news alert
%hr
%br
= form_for @news_alert, :url => 'set_news_alert' do |f|  
  .field
    = f.label :text, "News Alert Text"
    %div{:style => 'font-size: 80%; font-style: italic;'}
      Note: you can use 'a' tags for links, and 'strong' and 'em' tags for styling; no other tags, including linebreaks, will be maintained.
    = f.text_area :text

  .field
    = f.label :stop_at, "Automatically stop news alert at:"
    %div{:style => 'font-size: 80%; font-style: italic;'} Leave blank to never stop.
    = f.text_field :stop_at, :value => news_alert_date_value(@news_alert), :class => 'datetimepicker'

  = f.submit

%br
%br

- unless @news_alert.new?
  = form_tag 'kill_news_alert', :method => :post do
    %p 
      Kill news alert?
      = submit_tag 'Yeah, kill it!', :confirm => 'Are you sure?'

app/views/admin/user_metrics.html.haml
= title "User Metrics"

%h3 User Metrics

%div{style: 'margin-bottom: 12px;'}
  %h4 Average Active Users: (out of #{@user_count})
  %p Over the past day: #{@day_active_users} (%#{number_with_precision((@day_active_users.to_f / @user_count.to_f * 100), :precision => 2)})

  %p Over the past 7 days: #{@week_active_users} (%#{number_with_precision((@week_active_users.to_f / @user_count.to_f * 100), :precision => 2)})

  %p Over the past 30 days: #{@month_active_users} (%#{number_with_precision((@month_active_users.to_f / @user_count.to_f * 100), :precision => 2)})

%div{style: 'margin-bottom: 12px;'}
  %h4 New Users:
  %p Over the past day: #{@day_new_users}

  %p Over the past 7 days: #{@week_new_users}

  %p Over the past 30 days: #{@month_new_users}

%div{style: 'margin-bottom: 12px;'}
  %h4 User Retention (Percentage of users who signed up some time interval ago and were active within the past day)
  - if @day_new_users.eql? 0
    Over the past day: [No users joined within this time interval]
  - else
    Over the past day: %#{number_with_precision((@day_retained_users.to_f / @day_new_users.to_f * 100), :precision => 2)}
  %br
  - if @week_new_users.eql? 0
    Over the past 7 days: [No users joined within this time interval]
  - else
    Over the past 7 days: %#{number_with_precision((@week_retained_users.to_f / @week_new_users.to_f * 100), :precision => 2)}
  %br
  - if @month_new_users.eql? 0
    Over the past 30 days: [No users joined within this time interval]
  - else
    Over the past 30 days: %#{number_with_precision((@month_retained_users.to_f / @month_new_users.to_f * 100), :precision => 2)}

/ %div{style: 'margin-bottom: 12px;'}
/   %h4 User who submitted ideas:
/ %br
/ %h4 Users who submitted ideas:
/ Number of users who submitted: #{@other_metrics[:idea_submissions][:length].to_i} (%#{number_with_precision(@other_metrics[:idea_submissions][:length].to_f / @user_count.to_f * 100, :precision => 2)})
/ %br
/ Number of submissions: #{@other_metrics[:idea_submissions][:total].to_i}
/ %br
/ Most submissions by a single user: #{@other_metrics[:idea_submissions][:most].to_i}
/ %br
/ Average submissions per user: #{number_with_precision(@other_metrics[:idea_submissions][:average], :precision => 2)}
/ %br
/ Median submissions per user: #{number_with_precision(@other_metrics[:idea_submissions][:median], :precision => 2)}
/ %br

app/views/admin/users.html.haml
= title "View New User Stats - Admin - GameSprout"
= content_for(:extra_early_javascripts) do
  // Google graph API stuff
  = javascript_include_tag "http://www.google.com/jsapi"

%h3 Users - #{User.count} total
%br
%h3 New Users Daily

#admin-visualization-daily
%br
%br
%h3 Total Users (Not Counting Since Before 5/28/13)

#admin-visualization-total
%br
%br

%h3 Raw New User Data
#admin-user-vis-chart-data{:style => "height:#{[@result.count * 13, 100].max.to_s}px;"}
  %table
    %th Date
    %th Number of New Users
    - @result.reverse.each do |r|
      %tr
        %td #{r.first.first}
        %td #{r.first.last}