config/routes.rb
GamefactoryTest::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations"}

  # catch attempts to access /users/password with a get (in cases where you mess up on password reminder and then try to access url directly)
  get '/users/password' => redirect('/users/password/new')

  # home routes
  root :to => 'home#index'
  get '/feed' => 'home#feed'

  # -- legacy redirects (from the previous architecture/db)
  get '/ideas/build', to: redirect { |params, request| "/ideas/browse?#{request.query_string}" }

  # dashboard
  scope '/dashboard' do
    get '/counts_for_owned_ideas/(:view_date)' => 'dashboard#counts_for_owned_ideas'
    get '/counts_for_followed_ideas/(:view_date)' => 'dashboard#counts_for_followed_ideas'
    get '/counts_for_navigation/(:view_date)' => 'dashboard#counts_for_navigation'

    get '/users_ideas' => 'dashboard#users_ideas'
    get '/followed_ideas' => 'dashboard#followed_ideas'
    get '/news' => 'dashboard#news'
    get '/posts_made_or_commented_on' => 'dashboard#posts_made_or_commented_on'
    get '/mentions' => 'dashboard#mentions'
    get '/more/(:what)/(:page)' => 'dashboard#more'    
  end

  # custom user routes
  get '/profile', to: 'user_profiles#show', :as => :my_profile
  post '/profile/search', :to => 'user_profiles#search', :as => :search_for_user
  get '/profile(/:id)', to: 'user_profiles#show', :as => :user, :constraints => { :id => /.*/ }
  get '/notification_settings' => 'notification_settings#edit'
  post '/notification_settings' => 'notification_settings#update', :as => :update_notification_settings
  get '/user_details' => 'user_details#edit'
  post '/user_details' => 'user_details#update', :as => :update_user_details
  post '/save_selection' => 'user_api#save_selection'
  post '/save_view' => 'user_api#save_viewed'
  post '/search_users' => 'user_api#search_users'

  # static pages
  get '/about' => 'pages#about'
  get '/about_team' => 'pages#about_team'
  get '/terms' => 'pages#terms'
  get '/faq' => 'pages#faq'
  get '/funding_info' => 'pages#funding_info'
  get '/volunteers' => 'pages#volunteers'
  get '/dev_center' => 'pages#dev_center'
  get '/dev_center_learn' => 'pages#dev_center_learn'
  get '/dev_center_build' => 'pages#dev_center_build'
  get '/community' => 'pages#community'
  get '/help' => 'pages#help'
  get '/news' => 'pages#news' # list of all news items, seperate from the dashboard list of news items
  get '/thanks_signup' => 'pages#thanks_signup', :as => 'thanks_signup'
  get '/about_reputation(/:user)' => 'pages#reputation', :as => 'about_reputation'

  # admin pages
  scope '/admin' do
    get '' => 'admin#index', as: 'admin'
    get 'top_voted' => 'admin#top_voted'
    get 'users' => 'admin#users'
    get 'user_metrics' => 'admin#user_metrics'
    get 'homepage_features' => 'admin#homepage_features'
    get 'generate_email_list' => 'admin#generate_email_list'
    get 'idea_metrics' => 'admin#idea_metrics'

    post 'set_homepage_features' => 'admin#set_homepage_features'

    get 'new_admin', :controller => 'admin'
    post 'adminify', :controller => 'admin'

    get 'news_alert', :controller => 'admin'
    post 'set_news_alert', :controller => 'admin'
    put 'set_news_alert', :controller => 'admin'
    post 'kill_news_alert', :controller => 'admin'

    # file moderation
    get 'files' => 'admin_files#unchecked', :as => 'admin_files'
    get 'files/checked' => 'admin_files#checked', :as => 'admin_files_checked'
    post 'files/mark_checked' => 'admin_files#mark_checked', :as => 'admin_files_mark_checked'
  end

  resources :comments
  resources :posts do
    member do
      post 'vote'
      get 'more_comments/(:page)' => 'posts#more_comments', :as => :more_comments
      
      get 'upload_files' => 'posts#upload_files'
      post 'upload_completed' => 'posts#upload_completed'
    end
  end


  resources :ideas, :except => :index do
    resources :goals
    resources :design_docs

    collection do
      get 'browse' => 'ideas_collection#browse'
      get 'play' => 'ideas_collection#play'
      get 'help_out'=> 'ideas_collection#help_out'
      get 'search' => 'ideas_collection#search'

      get '/(:browsing_for)/more/(:page)' => 'ideas_collection#more', :as => 'more'
    end

    member do
      # -- special page for deleted ideas
      get 'deleted' => 'ideas#deleted'
      
      # -- design document routes
      get 'design_document'
      post 'add_gallery_image' => 'idea_details#add_gallery_image'
      post 'remove_gallery_image' => 'idea_details#remove_gallery_image'
      post 'edit_banner_image' => 'idea_details#edit_banner_image'
      post 'edit_details' => 'idea_details#edit_details'
      post 'add_gallery_demo' => 'idea_details#add_gallery_demo'
      post 'remove_gallery_demo' => 'idea_details#remove_gallery_demo'
      post 'select_featured_demo' => 'idea_details#select_featured_demo'

      # -- checklist
      get 'checklist'
      post 'checklist/toggle_task' => 'ideas#toggle_checklist_task'

      # -- show more posts
      get 'more_posts/(:page)' => 'ideas#more_posts'

      # -- follow/unfollow
      post 'follow' => 'follows#create'
      delete 'unfollow' => 'follows#destroy'

      # -- yes/un-yes
      post 'yes' => 'yeses#create'
      delete 'no' => 'yeses#destroy'
    end
  end

  # -- resolve a goal using a post
  post '/resolve_goal' => 'goals#resolve'

  resources :feedback, :except => [:destroy] do
    member do
      post 'change_logged'
    end

    collection do
      get 'thank_you'      
    end
  end

  resources :news_items do
    collection do
      get 'admin' => 'news_items#admin'
    end
  end

  # -- alternate site activity view
  get 'site_activity' => 'site_activity#index', :as => 'site_activity'
  get 'site_activity/more/(:page)' => 'site_activity#more'

  # Vanilla forum single sign on using jsConnect
  get 'forum/single_sign_on' => 'vanilla_forum#single_sign_on'
  get 'forum' => 'vanilla_forum#embedded_forum'

  # Generic file upload (not tied to a post directly, just to a user)
  get 'files/(:user)/all' => 'files#all', :as => 'all_files'
  get 'files/(:user)' => 'files#index', :as => 'files'
  post 'files/upload_complete' => 'files#upload_complete'  

  # test s3 direct file upload setup
  # get 'upload_files' => 'test#upload_files'
  # post 'upload_completed' => 'test#upload_completed'  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  after_filter :remember_viewed_dashboard

  def index
    if user_signed_in?
      @my_ideas = current_user.owned_ideas.not_deleted
      
      total_follows = current_user.followed_ideas.ideas.all(:order => :updated_at.desc)
      @total_follow_count = total_follows.count
      @my_follows = total_follows.all(:limit => 6)
    else
      a_week_ago = DateTime.now - 1.week
      @featured_games = Idea.active.all(:updated_at.gte => a_week_ago).take(4)
      if @featured_games.size < 4
        @featured_games += Idea.active.take(4)
        @featured_games = @featured_games.uniq.take(4)
      end
    end

    render :layout => 'application'
  end

  private
  def has_unviewed?(collection)
    not collection.first(:updated_at.gt => current_user.view_date).nil?
  end  

  def count_unviewed(collection, options={})
    if collection.first.is_a?(Idea)
      posts = collection.collect { |idea| idea.posts }.flatten
    else
      posts = collection
    end

    # if we haven't been forced to go to the database yet, we should be able to count faster
    if posts.is_a?(DataMapper::Collection) && !options[:count_comments]
      unviewed = posts.count(:updated_at.gt => current_user.view_date)
    else
      unviewed = posts.select { |post| not current_user.viewed?(post) }.size
    end

    if options[:count_comments]
      comments = posts.collect { |p| p.comments }.flatten
      unviewed += comments.select { |comment| not current_user.viewed?(comment) }.size
    end

    return unviewed
  end

  def remember_viewed_dashboard
    if user_signed_in?      
      current_user.last_viewed_dashboard_at = DateTime.now
      current_user.save
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_dashboard_idea_card.html.haml
%li.gameIdeaThmb
  %span.feedCountIco{:'data-idea-id' => idea.id}
  
  %a{:href => idea_path(idea)}
    %img{:src => idea.details.banner_image.nil? ? "/assets/default-idea.png" : idea.details.banner_image}
    - if idea.details.title.length > 32
      #{idea.details.title[0,31].rstrip}...
    
    - else
      #{idea.details.title}

app/views/home/_featured_games.html.haml
.grid.threecol
	= render :partial => 'ideas/browse/design_game_card', :collection => @featured_games, :as => :idea

app/views/home/_home_sign_up.html.haml
= form_for(User.new, :as => :user, :url => registration_path(:user)) do |f|
  #signUp.floatRight
    .signUpBkgd
    %h3 Create an Account for FREE!
    %label.signUpText.hiddenLabel{:for => "usernameField"}
      Username:
      %br
    
    = f.text_field :username, :placeholder => 'Username', :class => 'signUpInput', :autocomplete => :off
    %br

    = f.password_field :password, :placeholder => 'Password', :class => 'signUpInput', :autocomplete => :off
    %br
    
    = f.text_field :email, :placeholder => 'Email Address', :class => 'signUpInput', :autocomplete => :off

    %p.signUpText
      %a{:href => '', :'data-expander-target-id' => "under-18-area", :'data-expanded-text' => '(Click to close under 18 instructions.)',} Under 18? Click here.

    %div{:'data-expander-id' => 'under-18-area', :class => 'hiddenTxt'}
      %p.signUpText 
        If you're <strong>younger than 18 years of age</strong>, please have your parent or guardian 
        %a{:href => '#', :'data-open-dialog-id' => 'consent-dialog'} read the gamesprout consent form
        and sign below.

        = render :partial => 'shared/under_18_consent_dialog'
      
      = f.text_field :parental_signature, :placeholder => "Parent's Signature", :class => 'signUpInput'

    %p.signUpText You must read and accept the Terms of Use before creating an account.
    
    = f.check_box :terms
    = f.label :terms, :class => 'signUpText' do
      I have read and accept the #{link_to 'Terms of Use', :terms, :target => :blank, :style => 'color: #f90; text-decoration: underline;'}
    
    %a{:href => "#", :id => 'home-logged-out-submit-button'}
      .orangeBtn
        %p Sign Up

app/views/home/_homepage_logged_in.html.haml
%input#lastViewedDate{type: 'hidden', value: current_user.view_date}

%main#dashboard
  
  %section.user-info
    %img.avatar{:src => current_user.avatar? ? current_user.avatar : "/assets/default-avatar.png"}
    %h4
      = current_user.username
      - if current_user.admin?
        %span.badge.orange Staff

    %ul.unstyled.cmds
      - if current_user.admin?
        %li
          %a{:href => '/admin'}
            Admin
      %li
        %a{:href => my_profile_path}
          My Profile
      %li
        %a{:href => edit_user_registration_path}
          Account Settings
      %li
        %a{:href => destroy_user_session_path, :'data-method' => :delete}
          Sign Out

    %h1#feed-header
      //Content gets populated via js
      %span.header-text My Ideas
  
  .widget#feedButtonbar
    // Note: whichever button is set to activeFeedBtn will have its content loaded automatically
    %ul.unstyled.tabs
      
      %a{:href => "", :'data-feed-url' => 'news', :'data-selection' => "home_dash:news", :title => "The latest GameSprout news"}
        %li.feedBtn{:class => if_selected('home_dash', 'news', 'activeFeedBtn', :default => true)}
          %span.feedCountIco
          GameSprout News
      
      %a{:href => "", :'data-feed-url' => 'users_ideas', :'data-selection' => "home_dash:owned", :title => "Posts on ideas you currently own"}
        %li.feedBtn{:class => if_selected('home_dash', 'owned', 'activeFeedBtn')}
          %span.feedCountIco
          My Ideas
      
      %a{:href => "", :'data-feed-url' => 'posts_made_or_commented_on', :'data-selection' => "home_dash:conversations", :title => "Posts you made or commented on"}
        %li.feedBtn{:class => if_selected('home_dash', 'conversations', 'activeFeedBtn')}
          %span.feedCountIco
          My Conversations
        
      %a{:href => "", :'data-feed-url' => 'followed_ideas', :'data-selection' => "home_dash:following", :title => "Posts from ideas you follow"}
        %li.feedBtn{:class => if_selected('home_dash', 'following', 'activeFeedBtn')}
          %span.feedCountIco
          Ideas I'm Following

      %a{:href => "", :'data-feed-url' => 'mentions', :'data-selection' => "home_dash:mentions", :title => "Comments and News Items That Mention"}
        %li.feedBtn{:class => if_selected('home_dash', 'mentions', 'activeFeedBtn')}
          %span.feedCountIco
          Mentions

  %article#home-feed{:'data-async-scroll' => '/dashboard/more/', :'data-async-scroll-loader-element' => '#loading', :'data-async-qstring' => "?view_date=#{@current_user.view_date}"}

    #feed-content{:'data-async-scroll' => '/dashboard/more/', :'data-async-scroll-loader-element' => '#loading', :'data-async-qstring' => "?view_date=#{@current_user.view_date}"}
      // the #loading div is cloned and reused in the js -- you can put anything inside so long as the wrapping div remains unchanged.
      // Note that this is now used for both the first load of the feed (when selecting a tab), on on async scroll-paging of the feed.
      #loading.centered
        %img{src: '/assets/ajax-loader.gif'}
        Loading feed...


  %section.sidebar
    %article.summary
      %h5.section-header My Ideas
      %ul.unstyled#myIdeas
        - @my_ideas.each do |idea|
          = render :partial => "home/dashboard_idea_card", :locals => {idea: idea}
      
        %li#createNewIdea.gameIdeaThmb.new{:href => new_idea_path}
          %span.icon-create.green
          New Idea
          
      %h5.section-header Ideas I'm Following
      %ul.unstyled#following
        - @my_follows.each do |idea|
          = render :partial => "home/dashboard_idea_card", :locals => {idea: idea}


      - if @total_follow_count > @my_follows.size
        %ul.unstyled{style: 'clear: both;'}= link_to "See All Follows", user_path(current_user.username, :anchor => "follows")

app/views/home/_homepage_logged_out.html.haml
%main#home
  %article.hero
    %h1{ :style => 'margin-top: 1em; margin-bottom: 0.25em;' }
      site Shutdown notice
    %h3{ :style => 'margin-bottom: 1.2em' }
      On Sept. 14, 2015, GameSprout will no longer be available.
    %p.intro 
      Thank you so much for being part of the GameSprout community. Keep working to make your games a reality!
    %p.intro
      For more information, contact <a href="&#109;&#97;&#105;&#x6c;&#116;&#x6f;&#x3a;&#105;&#x6e;&#x66;&#x6f;&#64;&#x73;&#x63;&#104;&#101;&#108;&#x6c;&#x67;&#x61;&#x6d;&#101;&#115;&#x2e;&#x63;&#x6f;&#109;" target="_blank">info@schellgames.com</a>.
      
  %section.sign-up
    = render :partial => 'devise/shared/sign_up'
    %img{:src => "assets/splash-2.jpg"}

  %article.featured
    %h2 Featured Ideas:
    - @featured_games.each do |game|
      - begin
        %article.game-idea-block.cell.four-up
          %a.img-block{:href => idea_path(game)}
            %img{:src => game.details.banner_image? ? game.details.banner_image : "/assets/default-idea.png"}
          %h4.gamename= link_to game.title, game
          %p.byline
            = render :partial => 'ideas_collection/byline', :locals => {user: game.owner}
          %p.description.close= game.details.pitch

          = render :partial => 'ideas_collection/tags', :locals => {idea: game, simple_tags: (defined?(simple_tags) && simple_tags)}
      - rescue Exception => e
        - puts "Error on featured games: #{e.message}"
        - next

app/views/home/_ticker.html.haml
.news-ticker
  .news-image
    //= link_to image_tag('/assets/ticker-spreecast.jpg'), Rails.configuration.spreecast_url
    = link_to image_tag('/assets/ticker-beta.png'), about_path
    = link_to image_tag('/assets/ticker-idea.png'), new_idea_path
    = link_to image_tag('/assets/ticker-play.png'), play_ideas_path
    = link_to image_tag('/assets/ticker-art.png'), dev_center_path
    = link_to image_tag('/assets/ticker-prototype.png'), dev_center_path
    = link_to image_tag('/assets/ticker-blog.png'), Rails.configuration.jesses_blog_url
    = link_to image_tag('/assets/ticker-forums.png'), forum_path
  
  .news-footer
    / .news-story.first
    /   .news-name
    /     Watch us June 12th, 4pm EDT!
    /   .news-blurb
    /     Join us for a live Spreecast with the Frozen Frame team!
    /   .news-link
    /     = link_to "Visit our Spreecast Channel", about_path, :style => "color:#fff"

    .news-story.first
      .news-name
        GameSprout Beta is Live!
      .news-blurb
        Welcome to the GameSprout Beta site!
      .news-link
        = link_to "Learn how it works!", about_path, :style => "color:#fff"
    
    .news-story
      .news-name
        Submit A Game Idea
      .news-blurb
        Have your own great game idea? Submit it!
      .news-link
        = link_to "Go", new_idea_path, :style => "color:#fff"

    .news-story
      .news-name
        Play Prototypes
      .news-blurb
        Check out the latest game prototypes!
      .news-link
        = link_to "Go", play_ideas_path, :style => "color:#fff"

    .news-story
      .news-name
        Create Concept Art
      .news-blurb
        Help out your favorite idea by submitting your art!
      .news-link
        = link_to "Learn More", dev_center_path, :style => "color:#fff"

    .news-story
      .news-name
        Create a Demo
      .news-blurb
        Interested in programming? Submit your own demo!
      .news-link
        = link_to "Learn More", dev_center_path, :style => "color:#fff"

    .news-story
      .news-name
        Jesse's Gardening Tips
      .news-blurb
        Jesse Schell's blog with tips for game designers.
      .news-link
        = link_to "Go", Rails.configuration.jesses_blog_url, :style => "color:#fff"

    .news-story
      .news-name
        Check out the Forums
      .news-blurb
        Chat with other people on the site!
      .news-link
        = link_to "Go", forum_path, :style => "color:#fff"

    / The nav items will be automatically created inside this div by jquery.cycle
    #news-pager

app/views/home/index.html.haml
= render :partial => 'shared/news_alert'

- if user_signed_in?
  = render :partial => 'home/homepage_logged_in'
- else
  = render :partial => 'home/homepage_logged_out'

app/views/home/welcome.html.haml
%h4 Devise Links
- if user_signed_in?
  %p Signed in as #{current_user.username}. | #{link_to 'Sign Out', destroy_user_session_path, :method => :delete}
- else
  %p= link_to 'Sign In', new_user_session_path

%br
User count: #{User.count}
%br

%hr

- Idea.each do |idea|
  %strong #{idea.details.title} by #{idea.owner.username}
  %br

  Post count: #{idea.posts.count}
  %br
  %br

  .posts{style: 'margin-left: 20px;'}
    - idea.posts.each do |post|
      .post
        #{post.type} by #{post.user.username}

        %br
        Comment count: #{post.comments.count}
        .comments{style: 'margin-left: 20px;'}
          - post.comments.each do |comment|
            .comment
              Comment by #{comment.user.username}
      %br

  = link_to 'delete', idea_path(idea), :method => :delete
  %hr