config/routes.rb
GamefactoryTest::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations"}

  # catch attempts to access /users/password with a get (in cases where you mess up on password reminder and then try to access url directly)
  get '/users/password' => redirect('/users/password/new')

  # home routes
  root :to => 'home#index'
  get '/feed' => 'home#feed'

  # -- legacy redirects (from the previous architecture/db)
  get '/ideas/build', to: redirect { |params, request| "/ideas/browse?#{request.query_string}" }

  # dashboard
  scope '/dashboard' do
    get '/counts_for_owned_ideas/(:view_date)' => 'dashboard#counts_for_owned_ideas'
    get '/counts_for_followed_ideas/(:view_date)' => 'dashboard#counts_for_followed_ideas'
    get '/counts_for_navigation/(:view_date)' => 'dashboard#counts_for_navigation'

    get '/users_ideas' => 'dashboard#users_ideas'
    get '/followed_ideas' => 'dashboard#followed_ideas'
    get '/news' => 'dashboard#news'
    get '/posts_made_or_commented_on' => 'dashboard#posts_made_or_commented_on'
    get '/mentions' => 'dashboard#mentions'
    get '/more/(:what)/(:page)' => 'dashboard#more'    
  end

  # custom user routes
  get '/profile', to: 'user_profiles#show', :as => :my_profile
  post '/profile/search', :to => 'user_profiles#search', :as => :search_for_user
  get '/profile(/:id)', to: 'user_profiles#show', :as => :user, :constraints => { :id => /.*/ }
  get '/notification_settings' => 'notification_settings#edit'
  post '/notification_settings' => 'notification_settings#update', :as => :update_notification_settings
  get '/user_details' => 'user_details#edit'
  post '/user_details' => 'user_details#update', :as => :update_user_details
  post '/save_selection' => 'user_api#save_selection'
  post '/save_view' => 'user_api#save_viewed'
  post '/search_users' => 'user_api#search_users'

  # static pages
  get '/about' => 'pages#about'
  get '/about_team' => 'pages#about_team'
  get '/terms' => 'pages#terms'
  get '/faq' => 'pages#faq'
  get '/funding_info' => 'pages#funding_info'
  get '/volunteers' => 'pages#volunteers'
  get '/dev_center' => 'pages#dev_center'
  get '/dev_center_learn' => 'pages#dev_center_learn'
  get '/dev_center_build' => 'pages#dev_center_build'
  get '/community' => 'pages#community'
  get '/help' => 'pages#help'
  get '/news' => 'pages#news' # list of all news items, seperate from the dashboard list of news items
  get '/thanks_signup' => 'pages#thanks_signup', :as => 'thanks_signup'
  get '/about_reputation(/:user)' => 'pages#reputation', :as => 'about_reputation'

  # admin pages
  scope '/admin' do
    get '' => 'admin#index', as: 'admin'
    get 'top_voted' => 'admin#top_voted'
    get 'users' => 'admin#users'
    get 'user_metrics' => 'admin#user_metrics'
    get 'homepage_features' => 'admin#homepage_features'
    get 'generate_email_list' => 'admin#generate_email_list'
    get 'idea_metrics' => 'admin#idea_metrics'

    post 'set_homepage_features' => 'admin#set_homepage_features'

    get 'new_admin', :controller => 'admin'
    post 'adminify', :controller => 'admin'

    get 'news_alert', :controller => 'admin'
    post 'set_news_alert', :controller => 'admin'
    put 'set_news_alert', :controller => 'admin'
    post 'kill_news_alert', :controller => 'admin'

    # file moderation
    get 'files' => 'admin_files#unchecked', :as => 'admin_files'
    get 'files/checked' => 'admin_files#checked', :as => 'admin_files_checked'
    post 'files/mark_checked' => 'admin_files#mark_checked', :as => 'admin_files_mark_checked'
  end

  resources :comments
  resources :posts do
    member do
      post 'vote'
      get 'more_comments/(:page)' => 'posts#more_comments', :as => :more_comments
      
      get 'upload_files' => 'posts#upload_files'
      post 'upload_completed' => 'posts#upload_completed'
    end
  end


  resources :ideas, :except => :index do
    resources :goals
    resources :design_docs

    collection do
      get 'browse' => 'ideas_collection#browse'
      get 'play' => 'ideas_collection#play'
      get 'help_out'=> 'ideas_collection#help_out'
      get 'search' => 'ideas_collection#search'

      get '/(:browsing_for)/more/(:page)' => 'ideas_collection#more', :as => 'more'
    end

    member do
      # -- special page for deleted ideas
      get 'deleted' => 'ideas#deleted'
      
      # -- design document routes
      get 'design_document'
      post 'add_gallery_image' => 'idea_details#add_gallery_image'
      post 'remove_gallery_image' => 'idea_details#remove_gallery_image'
      post 'edit_banner_image' => 'idea_details#edit_banner_image'
      post 'edit_details' => 'idea_details#edit_details'
      post 'add_gallery_demo' => 'idea_details#add_gallery_demo'
      post 'remove_gallery_demo' => 'idea_details#remove_gallery_demo'
      post 'select_featured_demo' => 'idea_details#select_featured_demo'

      # -- checklist
      get 'checklist'
      post 'checklist/toggle_task' => 'ideas#toggle_checklist_task'

      # -- show more posts
      get 'more_posts/(:page)' => 'ideas#more_posts'

      # -- follow/unfollow
      post 'follow' => 'follows#create'
      delete 'unfollow' => 'follows#destroy'

      # -- yes/un-yes
      post 'yes' => 'yeses#create'
      delete 'no' => 'yeses#destroy'
    end
  end

  # -- resolve a goal using a post
  post '/resolve_goal' => 'goals#resolve'

  resources :feedback, :except => [:destroy] do
    member do
      post 'change_logged'
    end

    collection do
      get 'thank_you'      
    end
  end

  resources :news_items do
    collection do
      get 'admin' => 'news_items#admin'
    end
  end

  # -- alternate site activity view
  get 'site_activity' => 'site_activity#index', :as => 'site_activity'
  get 'site_activity/more/(:page)' => 'site_activity#more'

  # Vanilla forum single sign on using jsConnect
  get 'forum/single_sign_on' => 'vanilla_forum#single_sign_on'
  get 'forum' => 'vanilla_forum#embedded_forum'

  # Generic file upload (not tied to a post directly, just to a user)
  get 'files/(:user)/all' => 'files#all', :as => 'all_files'
  get 'files/(:user)' => 'files#index', :as => 'files'
  post 'files/upload_complete' => 'files#upload_complete'  

  # test s3 direct file upload setup
  # get 'upload_files' => 'test#upload_files'
  # post 'upload_completed' => 'test#upload_completed'  
end

app/models/feedback.rb
class Feedback
  include DataMapper::Resource
  timestamps :at

  property :id, Serial
  property :type, String, :required => true
  property :email, String
  property :content, String, :required => true, :length => 1000
  property :logged, Boolean, :default => false
  property :notes, String, :default => '', :length => 1000

  belongs_to :user, :required => false

  # -- class methods
  def self.types
    [:bug_report, :feedback, :help_request, :other]
  end

  def self.types_with_names
    self.types.collect { |t| [t.to_s.humanize.titleize, t] }
  end

  # -- scopes
  def self.visible
    all(:logged => false)
  end

  def self.newest_created
    all(:order => :created_at.desc)
  end

  def self.oldest_created
    all(:order => :created_at.asc)
  end

  def self.logged
    all(:logged => true).oldest_created()
  end

  
  # -- instance methods
  def shortened_content
    if content.size > 100
      content[0..100] + "..."
    else
      content
    end
  end

  def user?
    !user.nil?
  end
end

app/controllers/feedback_controller.rb
class FeedbackController < ApplicationController
  before_filter :user_must_be_admin!, :except => [:new, :create, :thank_you]
  before_filter :get_feedback, :only => [:show, :edit, :update, :change_logged]

  def index
    if not params[:commit].eql? "Filter"
      params[:view] = params[:commit]
    end
    
    case params[:category]
    when "Logged"
      @feedback = Feedback.logged.newest_created
    when "All"
      @feedback = Feedback.oldest_created
    else
      @feedback = Feedback.visible.newest_created
    end

    if not (params[:type].blank? || (params[:type].eql? "All"))
      @feedback = @feedback.delete_if {|f| not f.type.eql? params[:type]}
    end

    if not params[:owner].blank?
      search_email = nil
      search_user = nil
      if params[:owner].match(/\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/)
        search_email = params[:owner]
      else
        search_user = User.first(:username => params[:owner])
        if not search_user.nil?
          search_email = search_user.email
        end
      end
      @feedback = @feedback.delete_if {|f| not f.email.eql? search_email}
    end
  end

  def show    
  end

  def new
    @feedback = Feedback.new
  end

  def create    
    @feedback = Feedback.create(params[:feedback])
    @feedback.user = current_user if user_signed_in?

    if @feedback.save
      redirect_to :action => :thank_you
    else
      render :action => :new
    end
  end

  def edit
  end

  def update
    @feedback_item.notes = params[:feedback][:notes]

    if @feedback_item.save    
      redirect_to @feedback_item
    else
      render :action => :edit
    end
  end

  def thank_you
  end

  def change_logged
    if params[:action_to_take] == "log"
      @feedback_item.logged = true
      flash[:notice] = "Feedback item logged."
    elsif params[:action_to_take] == "unlog"
      @feedback_item.logged = false
      flash[:notice] = "Feedback item un-logged."
    end

    render :json => { success: @feedback_item.save }
  end

  private
  def get_feedback
    @feedback_item = Feedback.get(params[:id])
  end
end

app/helpers/feedback_helper.rb
module FeedbackHelper
end

app/views/feedback/_item.html.haml
.feedback-item{id: feedback_item.id}
  .type Type: #{feedback_item.type.to_s}
  - if feedback_item.user?
    .from From: #{feedback_item.user.username} (#{feedback_item.user.email})
  
  .email Email: #{feedback_item.email}
  .item-logged 
    Logged? #{feedback_item.logged? ? "Yes" : "No"}
    - if defined?(shorten)
      %input.action_url{type: 'hidden', value: change_logged_feedback_path(feedback_item)}
      - if feedback_item.logged?
        %a.btn{"data-feedback-action" => 'unlog', href: '#'} un-log
      - else
        %a.btn{"data-feedback-action" => 'log', href: '#'} log  
    
  .sent-on.small
    Created on #{get_formatted_date(feedback_item.created_at, :include_time => true)}
    (#{distance_of_time_in_words feedback_item.created_at, Time.zone.now} ago)
  
  - if defined?(shorten) && shorten
    .content.shortened.small= feedback_item.shortened_content
    .read-more= link_to 'view', feedback_path(feedback_item), class: 'btn'
  
  - else
    .content= feedback_item.content

app/views/feedback/edit.html.haml
- if @feedback_item.errors.any?
  There was an error saving the notes.

#feedback-show
  = link_to 'back to feedback item', @feedback_item, :class => "back"
  
  = render :partial => 'item', :locals => {feedback_item: @feedback_item}

  = form_for @feedback_item do |f|
    .field
      = f.label :notes
      = f.text_area :notes, {class: 'tinymce', 'data-editor-config' => 'admin'}

    = f.submit

app/views/feedback/index.html.haml
= title "View Feedback - Admin - GameSprout"

#feedback-index
  = form_tag  feedback_index_path, :method => :get do
    = hidden_field_tag "view", params[:view]
    %table
      %tr
        %td
          Logged Status:
        %td
          = select_tag "category", options_for_select(["Not Logged", "Logged", "All"], params[:category])
      %tr
        %td
          Type:
        %td
          - types = ["All"].push *(Feedback.types)
          = select_tag "type", options_for_select(types, params[:type])
      %tr
        %td
        %td
          = text_field_tag "owner", params[:owner], :placeholder => "Search by Username or Email..."
      %tr
        %td
        %td
          = submit_tag "Filter"

  - if @feedback.any?
    #feedback-items
      - @feedback.each do |feedback_item|
        = render :partial => 'item', :locals => {shorten: true, feedback_item: feedback_item}
    
  - else
    #no-feedback
      There are no feedback items to look at in this scope.

app/views/feedback/new.html.haml
= title "Contact Us - GameSprout"

= render :partial => 'shared/billboard', :locals => {title: "Contact Us", content: "Have a question? Find a bug? Let us know!",  img_url: "/assets/contact-us-header.png" }

%main.content#contact
  %p.intro
    You can email us at #{link_to 'gs-support@schellgames.com', 'mailto:gs-support@schellgames.com'}, talk to us via any of our social media pages (
    %a.social-button.fbLike{:href => Rails.configuration.facebook_url, :title => "Like GameSprout on Facebook"}
      Like GameSprout on Facebook
    
    %a.social-button.twitter{:href => Rails.configuration.twitter_url, :title => "Follow GameSprout on Twitter"}
      Follow GameSprout on Twitter
    ), or you can use the contact form below!

  #contact-form
    = render :partial => 'shared/errors', :locals => {doc: @feedback, centered: false}

    = form_for @feedback do |f|
      .field
        = f.label :email
        = f.text_field :email, {value: (user_signed_in? ? current_user.email : '')}

      .field
        = f.label :type, "Subject"
        = f.select :type, Feedback.types_with_names, {include_blank: "Please pick one", default: nil, :selected => params[:feedback_type]}

      .field
        = f.label :content, "Message"
        = f.text_area :content, {class: 'feedback', maxlength: 1000}

      = f.submit "Submit Feedback"

app/views/feedback/show.html.haml
= title "View Feedback - Admin - GameSprout"

#feedback-show
  = link_to 'back to feedback index', feedback_index_path, :class => "back"

  = render :partial => 'item', :locals => {feedback_item: @feedback_item}
  
  .title-small Admin Notes
  #notes= @feedback_item.notes.empty? ? "(none)" : admin_content(@feedback_item.notes)

  #actions    
    %input.action_url{type: 'hidden', value: change_logged_feedback_path}
    - if @feedback_item.logged?
      = link_to 'un-log feedback', '#', class: 'btn', "data-feedback-action" => 'unlog'
    - else
      = link_to 'log feedback', '#', class: 'btn', "data-feedback-action" => 'log'

    = link_to 'edit admin note', edit_feedback_path, class: 'btn'

app/views/feedback/thank_you.html.haml
= title "Thanks For Contacting Us - GameSprout"
%main.content#bugsubmitted
  %h1 Thanks for contacting us! 

  %p.intro
    If this is a help request, we will try to get back to you as soon as possible. If you're reporting a bug or providing feedback, <strong><em>thank you</em></strong>! Websites, like games, can only improve with iteration, and your feedback helps us improve the site. We'll try to fix bugs as quickly as we can, while overall feedback might take a little longer &mdash; but we're definitely listening!