config/routes.rb
GamefactoryTest::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations"}

  # catch attempts to access /users/password with a get (in cases where you mess up on password reminder and then try to access url directly)
  get '/users/password' => redirect('/users/password/new')

  # home routes
  root :to => 'home#index'
  get '/feed' => 'home#feed'

  # -- legacy redirects (from the previous architecture/db)
  get '/ideas/build', to: redirect { |params, request| "/ideas/browse?#{request.query_string}" }

  # dashboard
  scope '/dashboard' do
    get '/counts_for_owned_ideas/(:view_date)' => 'dashboard#counts_for_owned_ideas'
    get '/counts_for_followed_ideas/(:view_date)' => 'dashboard#counts_for_followed_ideas'
    get '/counts_for_navigation/(:view_date)' => 'dashboard#counts_for_navigation'

    get '/users_ideas' => 'dashboard#users_ideas'
    get '/followed_ideas' => 'dashboard#followed_ideas'
    get '/news' => 'dashboard#news'
    get '/posts_made_or_commented_on' => 'dashboard#posts_made_or_commented_on'
    get '/mentions' => 'dashboard#mentions'
    get '/more/(:what)/(:page)' => 'dashboard#more'    
  end

  # custom user routes
  get '/profile', to: 'user_profiles#show', :as => :my_profile
  post '/profile/search', :to => 'user_profiles#search', :as => :search_for_user
  get '/profile(/:id)', to: 'user_profiles#show', :as => :user, :constraints => { :id => /.*/ }
  get '/notification_settings' => 'notification_settings#edit'
  post '/notification_settings' => 'notification_settings#update', :as => :update_notification_settings
  get '/user_details' => 'user_details#edit'
  post '/user_details' => 'user_details#update', :as => :update_user_details
  post '/save_selection' => 'user_api#save_selection'
  post '/save_view' => 'user_api#save_viewed'
  post '/search_users' => 'user_api#search_users'

  # static pages
  get '/about' => 'pages#about'
  get '/about_team' => 'pages#about_team'
  get '/terms' => 'pages#terms'
  get '/faq' => 'pages#faq'
  get '/funding_info' => 'pages#funding_info'
  get '/volunteers' => 'pages#volunteers'
  get '/dev_center' => 'pages#dev_center'
  get '/dev_center_learn' => 'pages#dev_center_learn'
  get '/dev_center_build' => 'pages#dev_center_build'
  get '/community' => 'pages#community'
  get '/help' => 'pages#help'
  get '/news' => 'pages#news' # list of all news items, seperate from the dashboard list of news items
  get '/thanks_signup' => 'pages#thanks_signup', :as => 'thanks_signup'
  get '/about_reputation(/:user)' => 'pages#reputation', :as => 'about_reputation'

  # admin pages
  scope '/admin' do
    get '' => 'admin#index', as: 'admin'
    get 'top_voted' => 'admin#top_voted'
    get 'users' => 'admin#users'
    get 'user_metrics' => 'admin#user_metrics'
    get 'homepage_features' => 'admin#homepage_features'
    get 'generate_email_list' => 'admin#generate_email_list'
    get 'idea_metrics' => 'admin#idea_metrics'

    post 'set_homepage_features' => 'admin#set_homepage_features'

    get 'new_admin', :controller => 'admin'
    post 'adminify', :controller => 'admin'

    get 'news_alert', :controller => 'admin'
    post 'set_news_alert', :controller => 'admin'
    put 'set_news_alert', :controller => 'admin'
    post 'kill_news_alert', :controller => 'admin'

    # file moderation
    get 'files' => 'admin_files#unchecked', :as => 'admin_files'
    get 'files/checked' => 'admin_files#checked', :as => 'admin_files_checked'
    post 'files/mark_checked' => 'admin_files#mark_checked', :as => 'admin_files_mark_checked'
  end

  resources :comments
  resources :posts do
    member do
      post 'vote'
      get 'more_comments/(:page)' => 'posts#more_comments', :as => :more_comments
      
      get 'upload_files' => 'posts#upload_files'
      post 'upload_completed' => 'posts#upload_completed'
    end
  end


  resources :ideas, :except => :index do
    resources :goals
    resources :design_docs

    collection do
      get 'browse' => 'ideas_collection#browse'
      get 'play' => 'ideas_collection#play'
      get 'help_out'=> 'ideas_collection#help_out'
      get 'search' => 'ideas_collection#search'

      get '/(:browsing_for)/more/(:page)' => 'ideas_collection#more', :as => 'more'
    end

    member do
      # -- special page for deleted ideas
      get 'deleted' => 'ideas#deleted'
      
      # -- design document routes
      get 'design_document'
      post 'add_gallery_image' => 'idea_details#add_gallery_image'
      post 'remove_gallery_image' => 'idea_details#remove_gallery_image'
      post 'edit_banner_image' => 'idea_details#edit_banner_image'
      post 'edit_details' => 'idea_details#edit_details'
      post 'add_gallery_demo' => 'idea_details#add_gallery_demo'
      post 'remove_gallery_demo' => 'idea_details#remove_gallery_demo'
      post 'select_featured_demo' => 'idea_details#select_featured_demo'

      # -- checklist
      get 'checklist'
      post 'checklist/toggle_task' => 'ideas#toggle_checklist_task'

      # -- show more posts
      get 'more_posts/(:page)' => 'ideas#more_posts'

      # -- follow/unfollow
      post 'follow' => 'follows#create'
      delete 'unfollow' => 'follows#destroy'

      # -- yes/un-yes
      post 'yes' => 'yeses#create'
      delete 'no' => 'yeses#destroy'
    end
  end

  # -- resolve a goal using a post
  post '/resolve_goal' => 'goals#resolve'

  resources :feedback, :except => [:destroy] do
    member do
      post 'change_logged'
    end

    collection do
      get 'thank_you'      
    end
  end

  resources :news_items do
    collection do
      get 'admin' => 'news_items#admin'
    end
  end

  # -- alternate site activity view
  get 'site_activity' => 'site_activity#index', :as => 'site_activity'
  get 'site_activity/more/(:page)' => 'site_activity#more'

  # Vanilla forum single sign on using jsConnect
  get 'forum/single_sign_on' => 'vanilla_forum#single_sign_on'
  get 'forum' => 'vanilla_forum#embedded_forum'

  # Generic file upload (not tied to a post directly, just to a user)
  get 'files/(:user)/all' => 'files#all', :as => 'all_files'
  get 'files/(:user)' => 'files#index', :as => 'files'
  post 'files/upload_complete' => 'files#upload_complete'  

  # test s3 direct file upload setup
  # get 'upload_files' => 'test#upload_files'
  # post 'upload_completed' => 'test#upload_completed'  
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  POSTS_AT_ONCE = 4

  before_filter :must_be_signed_in_with_redirect, :except => [:show, :more_posts, :checklist, :design_document, :deleted]
  before_filter :find_idea, :except => [:new, :create]
  before_filter :must_own_idea, :only => [:edit, :update, :destroy]

  def show
    respond_to do |format|
      format.html {
        @discussion = Post.new(type: 'discussion', user: current_user, idea_id:  @idea.id)
        @poll = Post.new(type: 'poll', user: current_user, idea_id:  @idea.id)
        @art_collection = Post.new_art_collection(current_user, @idea.id)

        @browser_playable_prototype = Post.new(type: 'browser_playable_prototype', user: current_user, idea_id:  @idea.id)
        @downloadable_prototype = Post.new(type: 'downloadable_prototype', user: current_user, idea_id:  @idea.id)
        @video_prototype = Post.new(type: 'video_prototype', user: current_user, idea_id:  @idea.id)
      }

      format.json {
        hash = {}

        # details
        hash[:details] = @idea.details.attributes
        hash[:details][:image_links] = []
        @idea.details.image_links.each do |image_link|
          hash[:details][:image_links].push image_link
        end

        # design docs
        hash[:design_docs] = []
        @idea.design_docs.each do |design_doc|
          hash[:design_docs].push design_doc.attributes
        end

        # tags
        hash[:tags] = @idea.tag_list
        
        # posts
        hash[:posts] = []
        @idea.posts.each do |post|
          post_hash = post.attributes

          if post.is_art_collection?            
            post_hash[:image_links] = [] 
            post.image_links.each do |image_link|
              post_hash[:image_links].push image_link.attributes
            end
          end

          if post.is_poll?
            post_hash[:poll_options] = []
            post.poll_options.each do |poll_option|
              post_hash[:poll_options].push poll_option.attributes
            end
          end

          hash[:posts].push post_hash
        end        

        render :json => hash.to_json
      }
    end    
  end

  def more_posts
    page = params[:page].to_i
    min = IdeasController::POSTS_AT_ONCE * (page - 1)
    max = IdeasController::POSTS_AT_ONCE * page

    all_posts = @idea.posts
    posts = all_posts[min...max]
    html = render_to_string :partial => 'ideas/show/post', :collection => posts, :as => :post, :layout => false

    render :json => {
      html: html
    }
  end

  def checklist
    path = File.expand_path('./config/locales/checklist.en.yml')
    @checklist = YAML::load_file(path)

    # aggregate some information about task groups
    completed_tasks = @idea.tasks.inject({}) do |task_group_hash, task|
      task = task.last # iterating over a hash, so we get an array of structure: [key, value]; we just care about the value
      key = task["group_id"]
      task_group_hash[key] ||= 0
      task_group_hash[key] += 1 if task["checked"] == true

      task_group_hash
    end

    @task_group_info = @checklist["en"]["TaskGroups"].inject({}) do |hash, element|
      key = element["TaskGroupID"]
      
      total_tasks = element["SubGroups"].collect { |subgroup| subgroup["Tasks"] }.flatten      

      hash[key] = {
        task_count: total_tasks.count,
        completed: completed_tasks[key].nil? ? 0 : completed_tasks[key]
      }

      hash
    end
  end

  def toggle_checklist_task
    if user_signed_in? && @idea.owner == current_user
      task_hash = params["checklist_task"]
      taskGroupId = task_hash["taskGroupId"]
      subgroupName = task_hash["subgroupName"]
      taskId = task_hash["taskId"]

      task = @idea.tasks[taskId] || {}
      task["group_id"] = taskGroupId
      task["subgroup"] = subgroupName

      # toggle whether it's checked
      task["checked"] = !task["checked"]

      @idea.tasks[taskId] = task
      success = @idea.save
    else
      success = false
    end

    render :json => {
      success: success
    }
  end

  def deleted
    unless @idea.deleted
      redirect_to @idea
    end
  end

  # -- Idea CRUD
  def new
    @idea = Idea.new
    @idea.details = IdeaDetails.new
  end

  def edit
  end

  def create
    @idea = Idea.new
    @idea.details = IdeaDetails.new

    tags = params[:idea].delete("tags")
    tags = tags.split(',') if tags

    @idea.attributes = params[:idea]
    @idea.submitter = current_user
    @idea.owner = current_user

    tags = sanitize_tags_array(tags)
    tags.each do |tag_name|
      tag = Tag.first_or_create(name: tag_name)
      @idea.tags << tag
    end

    if @idea.save
      redirect_to design_document_idea_path(@idea)
    else
      render :action => :new
    end
  end

  def update
    # manually change title and pitch to avoid blowing away other things in @idea.details (featured demo, galleries, etc.)
    details = params[:idea][:details]
    @idea.details.title = details[:title]
    @idea.details.pitch = details[:pitch]

    current_tags = @idea.tags

    new_tags = []
    tags = params[:idea].delete("tags")
    tags = tags.split(',') if tags
    tags = sanitize_tags_array(tags)
    tags.each do |tag_name|
      tag = Tag.first_or_create(name: tag_name)
      new_tags << tag
    end

    removed_tags = current_tags - new_tags
    removed_tags.each do |removed_tag|
      removed_tag.taggings.each(&:destroy)
      removed_tag.destroy if removed_tag.taggings.none?
    end
    
    added_tags = new_tags - current_tags
    added_tags.each do |new_tag|
      @idea.tags << new_tag
    end
    
    if @idea.save
      redirect_to design_document_idea_path(@idea)
    else
      render :action => :edit
    end
  end

  def destroy
    # tags m:m relationship does not have a constraint defined (because it's using a gem), so we need to manually clear them
    # however, the :tags method is referencing some autoloaded information that needs to be clear out, otherwise destroy validation will fail
    # so after destroying tags, we have to reload the model
    # @idea.tag_taggings.destroy
    # @idea.reload
    # @idea.destroy

    # paranoid delete
    @idea.deleted = true
    @idea.deleted_by = current_user
    @idea.save
    
    flash[:notice] = "Idea successfully deleted. If this was a mistake, please contact GameSprout support: gs-support@schellgames.com"
    redirect_to :root
  end

  private
  def find_idea
    @idea = Idea.get(params[:id])
    
    # check in case an old url (back when this ran on mongo) is being used
    if @idea.nil? && !params[:id].nil?
      @idea = Idea.first(:moped_id => params[:id])
    end

    if @idea.deleted && params[:action] != "deleted"
      redirect_to deleted_idea_path(@idea)
    end
  end

  def must_own_idea
    unless @idea.owner == current_user
      render :nothing => true, :status => :unauthorized
    end
  end
end

app/helpers/ideas_helper.rb
module IdeasHelper
  def get_feed_icon(post)
    case post.type
    when "discussion"
      "discussion"
    when "poll"
      "poll"
    when "art_collection"
      "art"
    when "browser_playable_prototype", "video_prototype", "downloadable_prototype"
      "demo"
    else
      "unknown post type"
    end
  end

  def following?(idea)
    if user_signed_in?
      not current_user.followed_ideas.first(:idea_id => idea.id).nil?
    else
      false
    end
  end

  def browse_type_class
    actual_name = request.path_info.split('/')[2]

    # to prevent css issues, for now the original names are used instead of the new, clearer names
    case actual_name
    when "browse"
      "design"
    when "play"
      "play"
    when "help_out"
      "build"
    when "search"
      "search"
    end
  end

  def filter_for_url(filter)
    filter == "all" ? url_for(:filter_for => nil) : url_for(params.merge(:filter_for => filter))
  end

  def idea_banner(idea)
    idea.details.banner_image? ? idea.details.banner_image : "/assets/default-idea.png"
  end

  def prototype_banner(prototype)
    prototype.image ? prototype.image : "/assets/default-demo.png" #"http://placehold.it/175x120"
  end

  def search_text
    params[:query] ? {:value => params[:query]} : {:placeholder => "Search all games..."}
  end

  def user_can_delete_post?(post)
    return false unless user_signed_in?
    current_user.admin? || post.idea.owner == current_user || post.user == current_user
  end

  def user_can_edit_post?(post)
    return false unless user_signed_in?
    can_edit = current_user.admin? || post.user == current_user
    
    if post.is_poll? && !current_user.admin?
      can_edit = can_edit && !post.has_any_votes?
    end

    can_edit
  end

  def by_staff?(idea, post)
    is_admin = post.user.admin?
    is_owner = idea.owner == post.user

    is_admin and not is_owner
  end

  def commit_count_text(goal)
    c = goal.commitments
    if c.size == 1
      text = '1 person is'
    else
      text = "#{c.size} people are"
    end

    "#{text} working on this goal!"
  end

  def special_rateable_attribs(rateable, text_before_id, hash={})
    if rateable.hidden?
      h = {:class => 'hidden', :'data-expander-id' => "#{text_before_id}_#{rateable.id.to_s}"}
    else
      h = {}
    end

    h = h.merge(hash)
    return h
  end

  def advice_bar_phase(idea)
    unless idea.details.complete?
      return :incomplete_design_doc
    end

    if idea.goals.nil? || idea.goals.empty?
      return :ask_help
    end
    
    if idea.goals.where(:what_kind => :demo).count.eql? 0
      return :ask_demo
    end
    
    return :ongoing
  end

  def generate_browse_cache
    {:collection => @results, :order => @order_scope, :tags => @tags}
  end

  def facebook_script
    %Q{
      window.open(
        'https://www.facebook.com/sharer/sharer.php?u='+encodeURIComponent(location.href), 
        'facebook-share-dialog', 
        'width=626,height=436'); 
      return false;
    }
  end

  def twitter_script
    %Q{
        var width  = 575,
        height = 400,
        left   = ($(window).width()  - width)  / 2,
        top    = ($(window).height() - height) / 2,
        url    = 'http://twitter.com/share?text='+document.title+'&url='+location.href +'&hashtags=gamesprout',
        opts   = 'status=1' +
                 ',width='  + width  +
                 ',height=' + height +
                 ',top='    + top    +
                 ',left='   + left;
    
        window.open(url, 'twitter', opts);
     
        return false;

      }
  end

  def task_classes(task, idea)
    task_id = task["TaskID"]
    task = @idea.tasks[task_id]
    
    if task && task["checked"]
      on_off = "on"
    else
      on_off = "off"
    end

    if current_user && idea.owner == current_user
      owner = "owner"
    else
      owner = ""
    end

    "#{on_off} #{owner}"
  end

  def show_demo_url_field?
    @prototype.is_video? || (!@prototype.new? && !@prototype.will_upload_files)
  end
end

app/views/ideas/design_document/_add_demo.html.haml
#add-demo-gallery
	= form_tag add_gallery_demo_idea_path, :method => :post do
		%h3 Choose a Demo from your Activity Feed
		= label_tag :demo, "Select a demo that you would like to add to the gallery on your design document page."
		%br
		%select{:name => "demo", :multiple => ""}
			- idea.posts.prototypes.reverse.each do |demo|
				-if !idea.demo_gallery.include? demo.id.to_s
					%option{:value => demo.id} #{demo.title}
		%br
		= submit_tag "Choose Demo", class: 'btn btn-success', :id => 'bottom-submit'

	%br
	%em Note: if you want to create a demo, #{link_to 'go to your activity feed', idea_path(@idea, :anchor => 'activity-feed')} and select the demo tab!

app/views/ideas/design_document/_add_gallery_image.html.haml
= form_tag add_gallery_image_idea_path, :method => :post do
  = label_tag :url, "Image url"
  = text_field_tag :url, nil
  = submit_tag "Save Image", class: 'btn', :id => 'top-submit', :'data-add-gallery-image' => true
  %img.ajax-loader{src: '/assets/ajax-loader.gif', style: 'display: none;'}

app/views/ideas/design_document/_demos.html.haml
%section.demos
  %h5.section-header Demos
  %ul.unstyled
    - idea.demo_gallery.each do |demo|
      %li.thumb
        - if user_owns_idea?
          .editable
            = link_to image_tag("/assets/x-icon.png"), remove_gallery_demo_idea_path(:demo => demo.id), {:method => :post, :confirm => "Are you sure you want to remove this demo from the gallery?", class: 'btn rm-gallery-demo'}
          %a{:href => post_path(demo)}
            %img{:src => demo.image.nil? || demo.image.strip.empty? ? "/assets/default-demo.png" : demo.image, width: 250, height: 180}
        - else
          %a{:href => post_path(demo)}
            %img{:src => demo.image.nil? || demo.image.strip.empty? ? "/assets/default-demo.png" : demo.image, width: 250, height: 180}

    - if user_owns_idea?
      %li.thumb
        = link_to "+ Add Demo", '', {class: 'add', 'data-dialog-target-id' => ("demo" + idea.id.to_s)}
        .demo-dialog-content{title: "Add to Demo Gallery", id: ("demo" + idea.id.to_s), 'data-dialog-size' => 'auto'}
          = render :partial => '/ideas/design_document/add_demo', :locals => {idea: idea}

app/views/ideas/design_document/_design_docs.html.haml
%section.design-details
  %h5.section-header Additional Design Details
  %ul.unstyled.cmds
    - idea.design_docs.each do |add_doc|
      %li
        = link_to add_doc.title, idea_design_doc_path(@idea, add_doc.id), :class => "item"
        - if user_owns_idea?
          .controls
            &nbsp;
            = link_to 'Edit', edit_idea_design_doc_path(@idea, add_doc.id)
            |
            = link_to 'Delete', idea_design_doc_path(@idea, add_doc), {:method => :delete, :confirm => "Are you sure you want to delete " + add_doc.title, :title => 'Delete'}


    - if user_owns_idea?
      = link_to "+ Add Design Detail", new_idea_design_doc_path(@idea), :class => "add"

app/views/ideas/design_document/_details.html.haml
#design-details
  %section#core-platform
    - if !details.platform.nil? && !details.platform.empty?
      %h5.section-header Platform
      %p= details.platform

  %section#core-mechanics
    - if !details.mechanics.nil? && !details.mechanics.empty?
      %h5.section-header Core Mechanics
      = comment_content details.mechanics

  %section#core-aesthetics
    - if !details.aesthetics.nil? && !details.aesthetics.empty?
      %h5.section-header Look and Feel
      = comment_content details.aesthetics

  %section#core-favorite
    - if !details.favorite.nil? && !details.favorite.empty?
      %h5.section-header Your Favorite Thing
      = comment_content details.favorite

  = link_to 'Comment', @idea, :class => 'btn narrow'

app/views/ideas/design_document/_details_editable.html.haml
#design-details
  = form_tag edit_details_idea_path, :method => :post do
    //Platform
    %section#core-platform
      %h5.section-header.close 
        Platform
        %a.btn-edit-platform 
          Edit

      - if !details.platform.nil? && !details.platform.empty?
        = details.platform
      - else
        = "No platform information yet."

    %section#core-platform-edit
      %h5.section-header.close
        Platform

      = label_tag :platform, "Which platforms will be the game be for?"
      .instructions (ex. iOS, PC, console, web)
      
      .field
        = text_field_tag :platform, @idea.details.platform, :'data-limit-id' => 'platform'
        = render :partial => 'shared/char_limit', :locals => {limit_id: 'platform', max_chars: 600}

      %a.btn.toggled-off.btn-edit-platform.narrow Cancel
      = submit_tag "Save Changes", {class: 'toggled-off btn-save-platform btn narrow'}

  = form_tag edit_details_idea_path, :method => :post do
    //Mechanics
    %section#core-mechanics
      %h5.section-header.close
        Core Mechanics
        %a.btn-edit-mechanics 
          Edit
      - if !details.mechanics.nil? && !details.mechanics.empty?
        = comment_content details.mechanics
      - else
        = "No mechanics information yet."

    %section#core-mechanics-edit
      %h5.section-header.close
        Core Mechanics

      = label_tag :mechanics, "Describe your game's core mechanics"
      .instructions Core mechanics are the moment-to-moment actions that the player will be taking. Think of this as the heart of the game.

      .field
        = text_area_tag :mechanics, @idea.details.mechanics, :'data-limit-id' => 'mechanics'
        = render :partial => 'shared/char_limit', :locals => {limit_id: 'mechanics', max_chars: 600}

      %a.toggled-off.btn.narrow.btn-edit-mechanics Cancel
      = submit_tag "Save Changes", {class: 'toggled-off btn narrow btn-save-mechanics'}

  = form_tag edit_details_idea_path, :method => :post do
    //Aesthetics
    %section#core-aesthetics
      %h5.section-header 
        Look and Feel
        %a.btn-edit-aesthetics 
          Edit
      - if !details.aesthetics.nil? && !details.aesthetics.empty?
        = comment_content details.aesthetics
      - else
        = "No aesthetics information yet."

    %section#core-aesthetics-edit
      %h5.section-header 
        Look and Feel

      = label_tag :aesthetics, "Briefly describe what you imagine the game looks and feels like"
      .instructions Try adding some images to your gallery to help show what you imagine!

      .field
        = text_area_tag :aesthetics, @idea.details.aesthetics, :'data-limit-id' => 'aesthetics'
        = render :partial => 'shared/char_limit', :locals => {limit_id: 'aesthetics', max_chars: 600}

      %a.toggled-off.btn.narrow.btn-edit-aesthetics Cancel
      = submit_tag "Save Changes", {class: 'toggled-off btn narrow btn-save-aesthetics'}

  = form_tag edit_details_idea_path, :method => :post do
    //Favorite Thing
    %section#core-favorite
      %h5.section-header 
        Favorite Thing About This Idea (Wow Factor!)
        %a.btn-edit-favorite 
          Edit
      - if !details.favorite.nil? && !details.favorite.empty?
        = comment_content details.favorite
      - else
        = "No favorite thing information yet."

    %section#core-favorite-edit
      %h5.section-header 
        Favorite Thing About This Idea (Wow Factor!)

      = label_tag :favorite, "What's your favorite thing about this game?"
          
      .field
        = text_area_tag :favorite, @idea.details.favorite, :'data-limit-id' => 'favorite'
        = render :partial => 'shared/char_limit', :locals => {limit_id: 'favorite', max_chars: 600}

      %a.toggled-off.btn.narrow.btn-edit-favorite Cancel
      = submit_tag "Save Changes", {class: 'toggled-off btn narrow btn-save-favorite'}

app/views/ideas/design_document/_edit_banner_image.html.haml
= form_tag edit_banner_image_idea_path, :method => :post, :id => "edit-banner-image-form" do
	= label_tag :url, "Change your idea's banner image (540x370)"
	%br
	Url: 
	= text_field_tag :url, nil, :size => 40
	= submit_tag "Save Image", class: 'btn btn-success', :id => 'top-submit'

app/views/ideas/design_document/_edit_main_details.html.haml
= form_tag edit_details_idea_path, :method => :post do
	.field
		= label_tag :title, "Edit the title of your idea (40 characters max)"
		= text_field_tag :title, idea.details.title, {:maxlength => 40, :size => 40, class: 'title'}
	.field
		= label_tag :pitch, "Edit your idea's pitch (600 characters max)"
		= text_area_tag :pitch, idea.details.pitch, {:maxlength => 600, :size => "75x12", class: 'description'}
	= submit_tag "Save Idea Details"

app/views/ideas/design_document/_featured_demo.html.haml
%section.featured-demo
	- demo = idea.featured_demo
	- if !demo.nil?
		-if user_owns_idea?
			%a.btn.orange.narrow{:href => '', 'data-dialog-target-id' => ("featured" + idea.id.to_s)}
				Change Featured Demo

			.featured-dialog-content{title: "Feature a Demo", id: ("featured" + idea.id.to_s), 'data-dialog-size' => ''}
				= render :partial => '/ideas/design_document/select_featured_update', :locals => {idea: idea}

		%h4.section-header
			Featured Demo
		%time.post-date
			Demo Posted on #{demo.created_at.strftime("%B %d, %Y")}
		= render :partial => '/ideas/show/post_type_prototype', :locals => {idea: idea, post: demo}
	- else

		-if user_owns_idea?
			%h4.section-header
				Featured Demo
			.featured-area
				%p.no-demo.close There is no featured demo for this idea. Feature one from your activity feed!
				%a.btn.orange.stacked{:href => '', 'data-dialog-target-id' => ("featured" + idea.id.to_s)}
					Feature a Demo
				.featured-dialog-content{title: "Feature a Demo", id: ("featured" + idea.id.to_s), 'data-dialog-size' => ''}
					= render :partial => '/ideas/design_document/select_featured_update', :locals => {idea: idea}

app/views/ideas/design_document/_gallery.html.haml
%section.gallery
  %h5.section-header Gallery
  %ul.unstyled.thumbnails
    - unless idea.details.image_links.nil? || idea.details.image_links.empty?
      - idea.details.image_links.reverse.each do |image|
        %li.thumb
          - if user_owns_idea?
            .editable
              %a.gallery-img{:href => image.url, :rel => "lightbox[design_gallery]", :title => image.description.nil? ? "" : image.description, :style => "background-image: url(#{image.url})"}

              = link_to '', remove_gallery_image_idea_path(:image => image.id.to_s), {:method => :post, :confirm => "Are you sure you want to remove this image from the gallery?", class: 'icon-remove', :title => 'Remove'}
          - else
            %a.gallery-img{:href => image.url, :rel => "lightbox[design_gallery]", :title => image.description.nil? ? "" : image.description, :style => "background-image: url(#{image.url})"}
              
    
    - if user_owns_idea?
      %li.thumb.add
        = link_to '+ Add Image', '', {'data-dialog-target-id' => ("gallery" + idea.id.to_s)}

        .image-dialog-content{title: "Add an Image to the Gallery", id: ("gallery" + idea.id.to_s), 'data-dialog-size' => 'auto'}
          = render :partial => '/ideas/design_document/add_gallery_image', :locals => {idea: idea}

app/views/ideas/design_document/_select_featured_update.html.haml
#add-demo-featured
	= form_tag select_featured_demo_idea_path, :method => :post do
		%h3 Feature a Demo:
		= label_tag :demo, "Select a demo post from your activity feed that you'd like to feature on your design document page!"
		%br
		%select{:name => "demo", :multiple => ""}
			- idea.posts.prototypes.reverse.each do |demo|
				%option{:value => demo.id} #{demo.title}
		%br
		= submit_tag "Feature Demo", class: 'btn btn-success'
		= submit_tag "Remove Featured Demo", {class: 'btn btn-success'}